Delivered-To: t.fruehbeck@gmail.com
Received: by 2002:a5d:48cc:0:0:0:0:0 with SMTP id p12csp807831wrs;
        Sat, 23 Nov 2019 09:42:09 -0800 (PST)
X-Google-Smtp-Source: APXvYqx9WpRrYzGx6sQxWWm4ILymTRsYwVW9SkDylA8/xvoKE/5ouRapCDZtuCG7PdYV7UueG31Z
X-Received: by 2002:a7b:cf05:: with SMTP id l5mr22971541wmg.44.1574530929507;
        Sat, 23 Nov 2019 09:42:09 -0800 (PST)
ARC-Seal: i=1; a=rsa-sha256; t=1574530929; cv=none;
        d=google.com; s=arc-20160816;
        b=Y6cfT9jMbpzrqEDZUeyk2V0e/YxTSxcERzZlbVbSXMA5nUXhehqGHiRSMNlqt8HjwI
         W0LGlvtmkCVrALEjCRlLLwB540ueMe2NcGzgC9pu/ShBFdBmUmjmESHMNEHzTR5H7dW7
         E8KhY+qdhNVJ8wflBXgoOJvU6JZSHKsf+DhUGWx4EyutZk4KPZm50+5DBNzRf8fvBUz+
         EhoH1bL/ofmHrQkaZGzhLkAnF0WH69qxXxsKihCcRmXOZKUKoiWodllA1y3PvKTPvN9x
         4ulSP7wfAJoeItLquWyW8vlw7fnmhlp7hDe6AtWUlByVHUqv4s1MAeyExM+JfxM4dCuB
         sPUQ==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=mime-version:subject:message-id:to:from:date;
        bh=EQl9K8zcsS4t7aabDdkfuNUqGRsPBSIfVXSTpQScV6A=;
        b=vWT3JutaVFGh4droiEQiI+fxID8g0rEFm65qrlosIyXXZB2+yKM2BU4UyeVn1ctpHr
         htdkuS3bIL5pf2UYfCUdPyKHcBdQtZUw1GtW7bbsXj1uGTlEAfSoZZpLpLDmZ8SaBSFT
         xfWM5UDzzhlZnX+m1UYV0anfDg+iLSB5NXb9G9f0kXuZhCZj3bXqwNZlQdrxwRNvgvgf
         2/u84WZA+mmZDYD76g4Xy9xs0K5nGWwX877ZMjzS8gYKMb7QykuvvDjFO/uuKveO7u+g
         xciEcJHX2RjzpABObNcp5PAlHUp6fYStZRg00C1ryViN7LwVymB2ja8dq70G2pYP1+FV
         qovQ==
ARC-Authentication-Results: i=1; mx.google.com;
       spf=pass (google.com: domain of office@ontrail.at designates 46.38.249.72 as permitted sender) smtp.mailfrom=office@ontrail.at
Return-Path: <office@ontrail.at>
Received: from mxf948.netcup.net (mxf948.netcup.net. [46.38.249.72])
        by mx.google.com with ESMTPS id n26si1904877wmk.2.2019.11.23.09.42.09
        for <t.fruehbeck@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Sat, 23 Nov 2019 09:42:09 -0800 (PST)
Received-SPF: pass (google.com: domain of office@ontrail.at designates 46.38.249.72 as permitted sender) client-ip=46.38.249.72;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of office@ontrail.at designates 46.38.249.72 as permitted sender) smtp.mailfrom=office@ontrail.at
Date: Sat, 23 Nov 2019 09:42:09 -0800 (PST)
X-No-Relay: not in my network
X-No-Relay: not in my network
Received: from vlproap001.at.inside (fw21above.mobilkom.at [194.48.128.75])
	by mxf948.netcup.net (Postfix) with ESMTPSA id 119C82042C;
	Sat, 23 Nov 2019 18:42:09 +0100 (CET)
From: "Office@Pfadfinder-Baden" <office@ontrail.at>
To: thomas.fruehbeck@a1.at, t.fruehbeck@gmail.com
Message-ID: <1006272726.211.1574530928721@vlproap001.at.inside>
Subject: Pfadfinder Baden - Mitgliedsbeitrag Markus Blochberger
MIME-Version: 1.0
Content-Type: multipart/alternative; 
	boundary="----=_Part_210_795799445.1574530928699"

------=_Part_210_795799445.1574530928699
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable


Liebe Mitglieder, liebe Eltern!

Ich darf Sie im Namen des Vorstandes an die Bezahlung des Mitgliedsbeitrags=
 f=C3=BCr Markus Blochberger, der bis zum 31. Oktober f=C3=A4llig war, erin=
nern.

Die Mitgliedsbeitr=C3=A4ge 2019/20:&nbsp;
=E2=82=AC 80,- f=C3=BCr das erste Kind=20
=E2=82=AC 60,- f=C3=BCr das zweite Kind=20
=E2=82=AC 40,- f=C3=BCr jedes weitere Kind=20
&nbsp;
Wir bitten um =C3=9Cberweisung auf unser Gruppenkonto bei der Sparkasse Bad=
en:
Konto: "Pfadfindergruppe Baden", IBAN: AT112020500000007450, BIC: SPBDAT21.
Verwendungszweck: MG-Beitrag 2019/20, Markus Blochberger RaRo

Sollten Sie diese Zahlungserinnerung trotz Abmeldung Ihres Kindes von uns e=
rhalten, schreiben Sie uns bitte umgehend an&nbsp;vorstand@ontrail.at
Ich m=C3=B6chte darauf hinweisen, dass eine&nbsp;schriftliche Abmeldung&nbs=
p;bei den zust=C3=A4ndigen PfadfinderleiterInnen und beim Vorstand bis Ende=
 Oktober notwendig war, andernfalls w=C3=A4re der Mitgliedsbeitrag f=C3=BCr=
 das aktuelle Pfadfinderjahr zu leisten.&nbsp;
&nbsp;
Es ist uns wichtig, dass die Teilnahme am Pfadfinderleben f=C3=BCr jedes Ki=
nd m=C3=B6glich ist. Sollten Sie also Probleme mit der Bezahlung haben, ric=
hten Sie sich bitte unter&nbsp;vorstand@ontrail.at&nbsp;vertraulich an die =
Obfrau Veronika Schiller und wir finden eine L=C3=B6sung.
&nbsp;
Ein herzliches Gut Pfad
Veronika Schiller
(f=C3=BCr den Vorstand)

------=_Part_210_795799445.1574530928699
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<p style=3D"margin:0; text-align: center;"><img src=3D"data:image/png;base6=
4,iVBORw0KGgoAAAANSUhEUgAAAPoAAAA0CAMAAACU0NXLAAAAk1BMVEUAAADPk5NHr9Tnycn58=
fKkMzTSpaXn2NipP0CFyuLC5PHt1tfbrq7s5OSlNDXiy8uuTE2xT1C5Zma3XF3z5ORXtdcZm8nw=
+Ps4qNApocx1w97Df4BmvNu+cnOU0ObDd3i9amvNmJirQULVoKHXsbLhu7zR6/Tg8vij1+my3u3=
JhYa0WVrcvr7Ii4wKlMX///+fJidyz2oXAAAAAXRSTlMAQObYZgAAAAFiS0dEAIgFHUgAAAAJcE=
hZcwAACxMAAAsTAQCanBgAAAAHdElNRQfjCR0KBwcv1agNAAAI5UlEQVRo3u2a6ZaquBaAmedBE=
BBxngfA5P2frvdOQKFEK6f6/jjerqxlIQRS+ZI9iyT9ba2iP2i3HzTpF/0X/Rf9/wU9dxQB9FmJ=
bd+fxqycCUzWYI/GpiQtyrLXU5aG5McwSFmGogP/L9EdchJAL/kYZn/qtBRAr/mjIzbrXg+lNfa=
W8KUSHfgF+urgEpJ46z9CPxFHCH1UwSw3P0OvqpjSsPpC3qDDGFXl/yv0dUI01XVVjSRrcfR8Qk=
6ZCHopmTjVcARDLXzJH1FdxxnWOuxbKIUg1Ngv7S1KrT2TZqtu0NmMNyPcYANu12EF9zqF89qwq=
M4FflbGOrVCybeeBjb06i26R9w1DbQkoGuXeMLoF0JIIYZuULqXYqqPcPcByEIUmAqcx+2UJB/m=
D5PHLWUr0aBv4ASv+BS7QXFg5eBY40Uu8FylFsMDv0X3iAx/D4Ts2Ikniq4QMslEdb1EIkOygAk=
0AKZfwkxHyIVTqgx+9E2cK95uNOj1Qqe6XzXdIe+u/bvAc3SLDdgduOZP6B0r+Ix+JVf4OyYHlY=
wZ+1UQ3YZdn4qi6yGoJeptzcSgZDO06gWfYfvBrWRsPTNnsG6/qowR795LX9DL3qczcPVO1wNNx=
UPiybLHvqlaIIReADk5TYUEfo/y6Jdckh8z5ILeQecSep8x7nq9MdmsJSm0Ht3foD8Gfod+JRFa=
eC2Q5S1Zsf2/CqHPGbqYroOg46z0ffll16H1d72uzR76fdZoCkYbQfTHwO/QXZdtukxlmXoJ+66=
KmzlFEF1nFmkDqthFLzFo6aKjUQ5foMPHrDi28R36Y+B36My4rcmWejLdMgnwiBh6IarrVg06Po=
NZLkKc8oJaJkrBhuomWP0HNigxbOsb9LDZ9TgcRI+bgevOwG/Qt8y8e7D1KqyBi+sgi6MfhaM5H=
Z0S13WjMfmmzn1Si85vsKQX6GZrCuJmnCf0/sAzMXREVkHOd6o4ujKBXT/fz5RX6EbNNVgK43Jh=
1AbG2fEGj3ChrH3JBLXEj+RDpL6AG9ndbLJ1Y+pZ9x4ilLoOJTMuYcAKeg1+Lw76auC3Ai83fxB=
d1uBk9wa9mEzIMb1bOdh35tmnk0m6zD4tc2O+7Y5O7oZvEH2K2l2gcZueTpx9yVx8Oney4rPQo7=
FKAmbgqYvoKqrAYTx+gZ4T55ymjg2whcPRWUBnF5eC2B+EPvbY5A8RVQ+w84CtejRS2UVvPCjwl=
+KS3qYg8SflzNHJHC6nNyUl6cegBx5J5IMmr2RX9UDHCQi7dlBduKAd5IQcggH0HAUcTNqUsDgW=
2wUVociU48foeuBqV8hWGd9aA4cO6GuisaQ1gNz1qrnBgIVfglgvpzf7fGsEHiU+S49pcc5F0Nv=
4nAeboxDD2/LpjtASqkKUtP4JuqtB+JKs2nXYIbrX0q4grIs09Rk9c5RbfjpPj5eUtE2Zn9PjUr=
kt8z9GBy9u0AF0wQLMz9BlTNOiuxuLkoCQIInuLi/CYF7+ip4dIXyb5plNOg0rdJkC3OfX6GbF/=
/oddMnHAgwPW/ym2tLcUXYKMD47+JXJ0c2qTUN9Kax4AFC1cQDvqtolC6sB9EDDtHyMbmwry6uA=
yi4hqkyDFWQxKBMsf21zuEcYM7/Xptp2QU/HzMAtVfroWF7ikSeWX3zM3/QuOl7gBYdZU50w+B3=
dKsSIJbwhVmgQfYGiEuLjC8p2ndcnNk19YiGxYg5E+RI7H/lP6CuCgOMEv7lqokWBRogWRFqiup=
i/JWMW6a2+oqe3LH+krBDNgW2bnkH/87ToR3Q9dD67kpVpOuhAbEDPDELy0QgLMBYvwMDs9Vlbg=
LEQCO4sKY9VS53GXF866Cxg13Ue747ggt/81+oJ/eDyKDZYa3x/VURXuSxo64CtDHW9r37dyW5p=
frNv8/Q4YdY9T+eXSZaDNNg35Vjkw+gzJsbtp0HHipzVllOkNil7CHyz600BpmTHBc9OGPCsRfd=
nzfP7fq0HiznP6CqHUmWX63NyHUPjSSsIv8wtnKd20TP75BTgwhSHHG3wb0fw6fmSeXUMbJe3NL=
08nHsPvZYG0HntptF1rCQ+UvEOepvktkerhhXDp0ypRe8uX7fWU0mD6Jx4qxEeuuzYQd7xUIdoW=
74GPXQFUfMji1enAL0E46ZMb/nleLHnSoZLAGrgCKNXzI4xdKafYui8AMMX7AV6d6wB9F1j2bkj=
pzyEIxx1rTWWfvcVnbWTvUQXxxjntykIegZyDxd591QU/ZGYgoDGe0H0EaxY9R69Yov6Er312RF=
bgwgCVxR4Vqqgu9bHYXz7jN60swJtqdi2fbTPj8uT25+jd3R9/wp9wY5c17/Z9XasYfQraUM1+b=
AerzRPhfMtBLSr8frQuvOgrdI1NESknbvos7qLDiHa/hW6MWsKMJtB9Jhae52buCpuas3D6CHX9=
fAl+vZeewTPRpIrVbWDB/YdYnftXpu7cjt/R0eJnnyHnj7QmS/uoC/o/ceFJ4HvF2Ce0PsFmPoN=
OjcHI+kl+iNc4QZvTSLXjbjNazWchz0ddKxOnL5hP3Us/D6OQ6yiYEkFP/6s3OCxV4BhX6o4rvB=
Of1Hu8Q7jUYBpT8qaHc1ZGRvt4war1dTs86j1bOJy4/PH7/WeLnrQZicrtGmRdkD1P/Dvqza/Cf=
roGcZw5/fo9gdkbpHmcmu2g3COQLgO6DLYeJdw4x+5WvQ1fcnseaEsHec0BD1xHHs+/4h8PUqIF=
/GgliC65yE64cFrBMl89JyvXzghuHElVTottZXCvjiTTqXmr67SBDIEry6kLZq3JuwnCEjnsHDD=
rsnBcG2uv8/YOtrf+fnxb6/NjWVoGNQkLqK7EMgGa7w2flGRXQpq+ge9SyOTLf7mdv3urYps8s7=
BdX9z/hh0cGSrlff8G+tTgWoKAevcmQwZuaWdf+QbVDLZ7e5VmXfoCHkGQ1dABJsq+PfsLMHqY7=
zzmegBmDZX5A2q42tN771j8UHvzUVak6l+gz4XMnKf9cpgFIm9N4de3AYn3vdqoOpF9vui6C/6L=
/ov+i/6fwH9H7EY1FC2z/h9AAAAAElFTkSuQmCC"></p><p style=3D'margin:0;'>Liebe M=
itglieder, liebe Eltern!</p><p style=3D'margin:0;'><br></p><p style=3D'marg=
in:0;'>Ich darf Sie im Namen des Vorstandes an die <strong>Bezahlung des Mi=
tgliedsbeitrags f=C3=BCr Markus Blochberger, der bis zum 31. Oktober f=C3=
=A4llig war, </strong>erinnern.</p><p style=3D'margin:0;'><br></p><p style=
=3D'margin:0;'><span style=3D"background-color: transparent;">Die Mitglieds=
beitr=C3=A4ge 2019/20:</span><strong style=3D"background-color: transparent=
; color: rgb(31, 73, 125);">&nbsp;</strong></p><p style=3D'margin:0;'><stro=
ng>=E2=82=AC 80,- f=C3=BCr das erste Kind </strong></p><p style=3D'margin:0=
;'><strong>=E2=82=AC 60,- f=C3=BCr das zweite Kind </strong></p><p style=3D=
'margin:0;'><strong>=E2=82=AC 40,- f=C3=BCr jedes weitere Kind </strong></p=
><p style=3D'margin:0;'>&nbsp;</p><p style=3D'margin:0;'>Wir bitten um =C3=
=9Cberweisung auf unser Gruppenkonto bei der Sparkasse Baden:</p><p style=
=3D'margin:0;'><strong>Konto: "Pfadfindergruppe Baden", IBAN: AT11202050000=
0007450, BIC: SPBDAT21.</strong></p><p style=3D'margin:0;'><strong>Verwendu=
ngszweck: MG-Beitrag 2019/20, Markus Blochberger RaRo</strong></p><p style=
=3D'margin:0;'><br></p><p style=3D'margin:0;'>Sollten Sie diese Zahlungseri=
nnerung trotz Abmeldung Ihres Kindes von uns erhalten, schreiben Sie uns bi=
tte umgehend an&nbsp;<a href=3D"mailto:vorstand@ontrail.at" target=3D"_blan=
k" style=3D"color: rgb(17, 85, 204);">vorstand@ontrail.at</a></p><p style=
=3D'margin:0;'>Ich m=C3=B6chte darauf hinweisen, dass eine&nbsp;<u>schriftl=
iche Abmeldung</u>&nbsp;bei den zust=C3=A4ndigen PfadfinderleiterInnen und =
beim Vorstand bis Ende Oktober notwendig war, andernfalls w=C3=A4re der Mit=
gliedsbeitrag f=C3=BCr das aktuelle Pfadfinderjahr zu leisten.&nbsp;</p><p =
style=3D'margin:0;'>&nbsp;</p><p style=3D'margin:0;'>Es ist uns wichtig, da=
ss die Teilnahme am Pfadfinderleben f=C3=BCr jedes Kind m=C3=B6glich ist. S=
ollten Sie also Probleme mit der Bezahlung haben, richten Sie sich bitte un=
ter&nbsp;<a href=3D"mailto:vorstand@ontrail.at" target=3D"_blank" style=3D"=
color: rgb(17, 85, 204);">vorstand@ontrail.at</a>&nbsp;vertraulich an die O=
bfrau Veronika Schiller und wir finden eine L=C3=B6sung.</p><p style=3D'mar=
gin:0;'>&nbsp;</p><p style=3D'margin:0;'>Ein herzliches Gut Pfad</p><p styl=
e=3D'margin:0;'>Veronika Schiller</p><p style=3D'margin:0;'>(f=C3=BCr den V=
orstand)</p>
------=_Part_210_795799445.1574530928699--
