package at.tfr.pfad.model;
// Generated Feb 2, 2021, 9:27:45 PM by Hibernate Tools 5.2.11.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ActivityAud generated by hbm2java
 */
@Entity
@Table(name="ACTIVITY_AUD")
public class ActivityAud  implements java.io.Serializable {


     private ActivityAudId id;
     private Revinfo revinfo;
     private Byte revtype;
     private String comment;
     private Boolean commentMod;
     private Date end;
     private Boolean endMod;
     private String name;
     private Boolean nameMod;
     private Date start;
     private Boolean startMod;
     private String type;
     private Boolean typeMod;
     private Boolean bookingsMod;
     private Date changed;
     private Boolean changedMod;
     private String changedby;
     private Boolean changedbyMod;
     private Date created;
     private Boolean createdMod;
     private String createdby;
     private Boolean createdbyMod;
     private String status;
     private Boolean statusMod;
     private Double aconto;
     private Boolean acontoMod;
     private Double amount;
     private Boolean amountMod;

    public ActivityAud() {
    }

	
    public ActivityAud(ActivityAudId id, Revinfo revinfo) {
        this.id = id;
        this.revinfo = revinfo;
    }
    public ActivityAud(ActivityAudId id, Revinfo revinfo, Byte revtype, String comment, Boolean commentMod, Date end, Boolean endMod, String name, Boolean nameMod, Date start, Boolean startMod, String type, Boolean typeMod, Boolean bookingsMod, Date changed, Boolean changedMod, String changedby, Boolean changedbyMod, Date created, Boolean createdMod, String createdby, Boolean createdbyMod, String status, Boolean statusMod, Double aconto, Boolean acontoMod, Double amount, Boolean amountMod) {
       this.id = id;
       this.revinfo = revinfo;
       this.revtype = revtype;
       this.comment = comment;
       this.commentMod = commentMod;
       this.end = end;
       this.endMod = endMod;
       this.name = name;
       this.nameMod = nameMod;
       this.start = start;
       this.startMod = startMod;
       this.type = type;
       this.typeMod = typeMod;
       this.bookingsMod = bookingsMod;
       this.changed = changed;
       this.changedMod = changedMod;
       this.changedby = changedby;
       this.changedbyMod = changedbyMod;
       this.created = created;
       this.createdMod = createdMod;
       this.createdby = createdby;
       this.createdbyMod = createdbyMod;
       this.status = status;
       this.statusMod = statusMod;
       this.aconto = aconto;
       this.acontoMod = acontoMod;
       this.amount = amount;
       this.amountMod = amountMod;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="ID", nullable=false) ), 
        @AttributeOverride(name="rev", column=@Column(name="REV", nullable=false) ) } )
    public ActivityAudId getId() {
        return this.id;
    }
    
    public void setId(ActivityAudId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REV", nullable=false, insertable=false, updatable=false)
    public Revinfo getRevinfo() {
        return this.revinfo;
    }
    
    public void setRevinfo(Revinfo revinfo) {
        this.revinfo = revinfo;
    }

    
    @Column(name="REVTYPE")
    public Byte getRevtype() {
        return this.revtype;
    }
    
    public void setRevtype(Byte revtype) {
        this.revtype = revtype;
    }

    
    @Column(name="COMMENT")
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }

    
    @Column(name="COMMENT_MOD")
    public Boolean getCommentMod() {
        return this.commentMod;
    }
    
    public void setCommentMod(Boolean commentMod) {
        this.commentMod = commentMod;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="END", length=8)
    public Date getEnd() {
        return this.end;
    }
    
    public void setEnd(Date end) {
        this.end = end;
    }

    
    @Column(name="END_MOD")
    public Boolean getEndMod() {
        return this.endMod;
    }
    
    public void setEndMod(Boolean endMod) {
        this.endMod = endMod;
    }

    
    @Column(name="NAME")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="NAME_MOD")
    public Boolean getNameMod() {
        return this.nameMod;
    }
    
    public void setNameMod(Boolean nameMod) {
        this.nameMod = nameMod;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="START", length=8)
    public Date getStart() {
        return this.start;
    }
    
    public void setStart(Date start) {
        this.start = start;
    }

    
    @Column(name="START_MOD")
    public Boolean getStartMod() {
        return this.startMod;
    }
    
    public void setStartMod(Boolean startMod) {
        this.startMod = startMod;
    }

    
    @Column(name="TYPE")
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="TYPE_MOD")
    public Boolean getTypeMod() {
        return this.typeMod;
    }
    
    public void setTypeMod(Boolean typeMod) {
        this.typeMod = typeMod;
    }

    
    @Column(name="BOOKINGS_MOD")
    public Boolean getBookingsMod() {
        return this.bookingsMod;
    }
    
    public void setBookingsMod(Boolean bookingsMod) {
        this.bookingsMod = bookingsMod;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CHANGED", length=23)
    public Date getChanged() {
        return this.changed;
    }
    
    public void setChanged(Date changed) {
        this.changed = changed;
    }

    
    @Column(name="CHANGED_MOD")
    public Boolean getChangedMod() {
        return this.changedMod;
    }
    
    public void setChangedMod(Boolean changedMod) {
        this.changedMod = changedMod;
    }

    
    @Column(name="CHANGEDBY")
    public String getChangedby() {
        return this.changedby;
    }
    
    public void setChangedby(String changedby) {
        this.changedby = changedby;
    }

    
    @Column(name="CHANGEDBY_MOD")
    public Boolean getChangedbyMod() {
        return this.changedbyMod;
    }
    
    public void setChangedbyMod(Boolean changedbyMod) {
        this.changedbyMod = changedbyMod;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    
    @Column(name="CREATED_MOD")
    public Boolean getCreatedMod() {
        return this.createdMod;
    }
    
    public void setCreatedMod(Boolean createdMod) {
        this.createdMod = createdMod;
    }

    
    @Column(name="CREATEDBY")
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    
    @Column(name="CREATEDBY_MOD")
    public Boolean getCreatedbyMod() {
        return this.createdbyMod;
    }
    
    public void setCreatedbyMod(Boolean createdbyMod) {
        this.createdbyMod = createdbyMod;
    }

    
    @Column(name="STATUS")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="STATUS_MOD")
    public Boolean getStatusMod() {
        return this.statusMod;
    }
    
    public void setStatusMod(Boolean statusMod) {
        this.statusMod = statusMod;
    }

    
    @Column(name="ACONTO", precision=17, scale=0)
    public Double getAconto() {
        return this.aconto;
    }
    
    public void setAconto(Double aconto) {
        this.aconto = aconto;
    }

    
    @Column(name="ACONTO_MOD")
    public Boolean getAcontoMod() {
        return this.acontoMod;
    }
    
    public void setAcontoMod(Boolean acontoMod) {
        this.acontoMod = acontoMod;
    }

    
    @Column(name="AMOUNT", precision=17, scale=0)
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    
    @Column(name="AMOUNT_MOD")
    public Boolean getAmountMod() {
        return this.amountMod;
    }
    
    public void setAmountMod(Boolean amountMod) {
        this.amountMod = amountMod;
    }




}


