package at.tfr.pfad.model;
// Generated Feb 2, 2021, 9:27:45 PM by Hibernate Tools 5.2.11.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BookingAud generated by hbm2java
 */
@Entity
@Table(name="BOOKING_AUD")
public class BookingAud  implements java.io.Serializable {


     private BookingAudId id;
     private Revinfo revinfo;
     private Byte revtype;
     private String comment;
     private Boolean commentMod;
     private Long activityId;
     private Boolean activityMod;
     private Long memberId;
     private Boolean memberMod;
     private Boolean paymentsMod;
     private Date changed;
     private Boolean changedMod;
     private String changedby;
     private Boolean changedbyMod;
     private Date created;
     private Boolean createdMod;
     private String createdby;
     private Boolean createdbyMod;
     private String status;
     private Boolean statusMod;
     private Long squadId;
     private Boolean squadMod;
     private Boolean activityidMod;
     private Boolean memberidMod;
     private Boolean squadidMod;
     private Boolean registered;
     private Boolean registeredMod;

    public BookingAud() {
    }

	
    public BookingAud(BookingAudId id, Revinfo revinfo) {
        this.id = id;
        this.revinfo = revinfo;
    }
    public BookingAud(BookingAudId id, Revinfo revinfo, Byte revtype, String comment, Boolean commentMod, Long activityId, Boolean activityMod, Long memberId, Boolean memberMod, Boolean paymentsMod, Date changed, Boolean changedMod, String changedby, Boolean changedbyMod, Date created, Boolean createdMod, String createdby, Boolean createdbyMod, String status, Boolean statusMod, Long squadId, Boolean squadMod, Boolean activityidMod, Boolean memberidMod, Boolean squadidMod, Boolean registered, Boolean registeredMod) {
       this.id = id;
       this.revinfo = revinfo;
       this.revtype = revtype;
       this.comment = comment;
       this.commentMod = commentMod;
       this.activityId = activityId;
       this.activityMod = activityMod;
       this.memberId = memberId;
       this.memberMod = memberMod;
       this.paymentsMod = paymentsMod;
       this.changed = changed;
       this.changedMod = changedMod;
       this.changedby = changedby;
       this.changedbyMod = changedbyMod;
       this.created = created;
       this.createdMod = createdMod;
       this.createdby = createdby;
       this.createdbyMod = createdbyMod;
       this.status = status;
       this.statusMod = statusMod;
       this.squadId = squadId;
       this.squadMod = squadMod;
       this.activityidMod = activityidMod;
       this.memberidMod = memberidMod;
       this.squadidMod = squadidMod;
       this.registered = registered;
       this.registeredMod = registeredMod;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="ID", nullable=false) ), 
        @AttributeOverride(name="rev", column=@Column(name="REV", nullable=false) ) } )
    public BookingAudId getId() {
        return this.id;
    }
    
    public void setId(BookingAudId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REV", nullable=false, insertable=false, updatable=false)
    public Revinfo getRevinfo() {
        return this.revinfo;
    }
    
    public void setRevinfo(Revinfo revinfo) {
        this.revinfo = revinfo;
    }

    
    @Column(name="REVTYPE")
    public Byte getRevtype() {
        return this.revtype;
    }
    
    public void setRevtype(Byte revtype) {
        this.revtype = revtype;
    }

    
    @Column(name="COMMENT")
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }

    
    @Column(name="COMMENT_MOD")
    public Boolean getCommentMod() {
        return this.commentMod;
    }
    
    public void setCommentMod(Boolean commentMod) {
        this.commentMod = commentMod;
    }

    
    @Column(name="ACTIVITY_ID")
    public Long getActivityId() {
        return this.activityId;
    }
    
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    
    @Column(name="ACTIVITY_MOD")
    public Boolean getActivityMod() {
        return this.activityMod;
    }
    
    public void setActivityMod(Boolean activityMod) {
        this.activityMod = activityMod;
    }

    
    @Column(name="MEMBER_ID")
    public Long getMemberId() {
        return this.memberId;
    }
    
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    
    @Column(name="MEMBER_MOD")
    public Boolean getMemberMod() {
        return this.memberMod;
    }
    
    public void setMemberMod(Boolean memberMod) {
        this.memberMod = memberMod;
    }

    
    @Column(name="PAYMENTS_MOD")
    public Boolean getPaymentsMod() {
        return this.paymentsMod;
    }
    
    public void setPaymentsMod(Boolean paymentsMod) {
        this.paymentsMod = paymentsMod;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CHANGED", length=23)
    public Date getChanged() {
        return this.changed;
    }
    
    public void setChanged(Date changed) {
        this.changed = changed;
    }

    
    @Column(name="CHANGED_MOD")
    public Boolean getChangedMod() {
        return this.changedMod;
    }
    
    public void setChangedMod(Boolean changedMod) {
        this.changedMod = changedMod;
    }

    
    @Column(name="CHANGEDBY")
    public String getChangedby() {
        return this.changedby;
    }
    
    public void setChangedby(String changedby) {
        this.changedby = changedby;
    }

    
    @Column(name="CHANGEDBY_MOD")
    public Boolean getChangedbyMod() {
        return this.changedbyMod;
    }
    
    public void setChangedbyMod(Boolean changedbyMod) {
        this.changedbyMod = changedbyMod;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    
    @Column(name="CREATED_MOD")
    public Boolean getCreatedMod() {
        return this.createdMod;
    }
    
    public void setCreatedMod(Boolean createdMod) {
        this.createdMod = createdMod;
    }

    
    @Column(name="CREATEDBY")
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    
    @Column(name="CREATEDBY_MOD")
    public Boolean getCreatedbyMod() {
        return this.createdbyMod;
    }
    
    public void setCreatedbyMod(Boolean createdbyMod) {
        this.createdbyMod = createdbyMod;
    }

    
    @Column(name="STATUS")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="STATUS_MOD")
    public Boolean getStatusMod() {
        return this.statusMod;
    }
    
    public void setStatusMod(Boolean statusMod) {
        this.statusMod = statusMod;
    }

    
    @Column(name="SQUAD_ID")
    public Long getSquadId() {
        return this.squadId;
    }
    
    public void setSquadId(Long squadId) {
        this.squadId = squadId;
    }

    
    @Column(name="SQUAD_MOD")
    public Boolean getSquadMod() {
        return this.squadMod;
    }
    
    public void setSquadMod(Boolean squadMod) {
        this.squadMod = squadMod;
    }

    
    @Column(name="ACTIVITYID_MOD")
    public Boolean getActivityidMod() {
        return this.activityidMod;
    }
    
    public void setActivityidMod(Boolean activityidMod) {
        this.activityidMod = activityidMod;
    }

    
    @Column(name="MEMBERID_MOD")
    public Boolean getMemberidMod() {
        return this.memberidMod;
    }
    
    public void setMemberidMod(Boolean memberidMod) {
        this.memberidMod = memberidMod;
    }

    
    @Column(name="SQUADID_MOD")
    public Boolean getSquadidMod() {
        return this.squadidMod;
    }
    
    public void setSquadidMod(Boolean squadidMod) {
        this.squadidMod = squadidMod;
    }

    
    @Column(name="REGISTERED")
    public Boolean getRegistered() {
        return this.registered;
    }
    
    public void setRegistered(Boolean registered) {
        this.registered = registered;
    }

    
    @Column(name="REGISTERED_MOD")
    public Boolean getRegisteredMod() {
        return this.registeredMod;
    }
    
    public void setRegisteredMod(Boolean registeredMod) {
        this.registeredMod = registeredMod;
    }




}


