package at.tfr.pfad.model;
// Generated Feb 2, 2021, 9:27:45 PM by Hibernate Tools 5.2.11.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FunctionAud generated by hbm2java
 */
@Entity
@Table(name="FUNCTION_AUD")
public class FunctionAud  implements java.io.Serializable {


     private FunctionAudId id;
     private Revinfo revinfo;
     private Byte revtype;
     private Boolean exportreg;
     private Boolean exportregMod;
     private String function;
     private Boolean functionMod;
     private String key;
     private Boolean keyMod;
     private Boolean free;
     private Boolean freeMod;
     private boolean leader;
     private Boolean leaderMod;
     private boolean nofunction;
     private Boolean nofunctionMod;
     private String sex;
     private Boolean sexMod;

    public FunctionAud() {
    }

	
    public FunctionAud(FunctionAudId id, Revinfo revinfo, boolean leader, boolean nofunction) {
        this.id = id;
        this.revinfo = revinfo;
        this.leader = leader;
        this.nofunction = nofunction;
    }
    public FunctionAud(FunctionAudId id, Revinfo revinfo, Byte revtype, Boolean exportreg, Boolean exportregMod, String function, Boolean functionMod, String key, Boolean keyMod, Boolean free, Boolean freeMod, boolean leader, Boolean leaderMod, boolean nofunction, Boolean nofunctionMod, String sex, Boolean sexMod) {
       this.id = id;
       this.revinfo = revinfo;
       this.revtype = revtype;
       this.exportreg = exportreg;
       this.exportregMod = exportregMod;
       this.function = function;
       this.functionMod = functionMod;
       this.key = key;
       this.keyMod = keyMod;
       this.free = free;
       this.freeMod = freeMod;
       this.leader = leader;
       this.leaderMod = leaderMod;
       this.nofunction = nofunction;
       this.nofunctionMod = nofunctionMod;
       this.sex = sex;
       this.sexMod = sexMod;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="ID", nullable=false) ), 
        @AttributeOverride(name="rev", column=@Column(name="REV", nullable=false) ) } )
    public FunctionAudId getId() {
        return this.id;
    }
    
    public void setId(FunctionAudId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REV", nullable=false, insertable=false, updatable=false)
    public Revinfo getRevinfo() {
        return this.revinfo;
    }
    
    public void setRevinfo(Revinfo revinfo) {
        this.revinfo = revinfo;
    }

    
    @Column(name="REVTYPE")
    public Byte getRevtype() {
        return this.revtype;
    }
    
    public void setRevtype(Byte revtype) {
        this.revtype = revtype;
    }

    
    @Column(name="EXPORTREG")
    public Boolean getExportreg() {
        return this.exportreg;
    }
    
    public void setExportreg(Boolean exportreg) {
        this.exportreg = exportreg;
    }

    
    @Column(name="EXPORTREG_MOD")
    public Boolean getExportregMod() {
        return this.exportregMod;
    }
    
    public void setExportregMod(Boolean exportregMod) {
        this.exportregMod = exportregMod;
    }

    
    @Column(name="FUNCTION")
    public String getFunction() {
        return this.function;
    }
    
    public void setFunction(String function) {
        this.function = function;
    }

    
    @Column(name="FUNCTION_MOD")
    public Boolean getFunctionMod() {
        return this.functionMod;
    }
    
    public void setFunctionMod(Boolean functionMod) {
        this.functionMod = functionMod;
    }

    
    @Column(name="KEY")
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }

    
    @Column(name="KEY_MOD")
    public Boolean getKeyMod() {
        return this.keyMod;
    }
    
    public void setKeyMod(Boolean keyMod) {
        this.keyMod = keyMod;
    }

    
    @Column(name="FREE")
    public Boolean getFree() {
        return this.free;
    }
    
    public void setFree(Boolean free) {
        this.free = free;
    }

    
    @Column(name="FREE_MOD")
    public Boolean getFreeMod() {
        return this.freeMod;
    }
    
    public void setFreeMod(Boolean freeMod) {
        this.freeMod = freeMod;
    }

    
    @Column(name="LEADER", nullable=false)
    public boolean isLeader() {
        return this.leader;
    }
    
    public void setLeader(boolean leader) {
        this.leader = leader;
    }

    
    @Column(name="LEADER_MOD")
    public Boolean getLeaderMod() {
        return this.leaderMod;
    }
    
    public void setLeaderMod(Boolean leaderMod) {
        this.leaderMod = leaderMod;
    }

    
    @Column(name="NOFUNCTION", nullable=false)
    public boolean isNofunction() {
        return this.nofunction;
    }
    
    public void setNofunction(boolean nofunction) {
        this.nofunction = nofunction;
    }

    
    @Column(name="NOFUNCTION_MOD")
    public Boolean getNofunctionMod() {
        return this.nofunctionMod;
    }
    
    public void setNofunctionMod(Boolean nofunctionMod) {
        this.nofunctionMod = nofunctionMod;
    }

    
    @Column(name="SEX")
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }

    
    @Column(name="SEX_MOD")
    public Boolean getSexMod() {
        return this.sexMod;
    }
    
    public void setSexMod(Boolean sexMod) {
        this.sexMod = sexMod;
    }




}


