package at.tfr.pfad.model;
// Generated Feb 2, 2021, 9:27:45 PM by Hibernate Tools 5.2.11.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MailtemplateAud generated by hbm2java
 */
@Entity
@Table(name="MAILTEMPLATE_AUD")
public class MailtemplateAud  implements java.io.Serializable {


     private MailtemplateAudId id;
     private Revinfo revinfo;
     private Byte revtype;
     private String query;
     private Boolean queryMod;
     private String subject;
     private Boolean subjectMod;
     private String text;
     private Boolean textMod;
     private String name;
     private Boolean nameMod;
     private Date changed;
     private Boolean changedMod;
     private String changedby;
     private Boolean changedbyMod;
     private Date created;
     private Boolean createdMod;
     private String createdby;
     private Boolean createdbyMod;
     private String owner;
     private Boolean ownerMod;
     private Boolean bcc;
     private Boolean bccMod;
     private Boolean cc;
     private Boolean ccMod;
     private Boolean savetext;
     private Boolean savetextMod;
     private Boolean sms;
     private Boolean smsMod;
     private Boolean alternativetext;
     private Boolean alternativetextMod;

    public MailtemplateAud() {
    }

	
    public MailtemplateAud(MailtemplateAudId id, Revinfo revinfo) {
        this.id = id;
        this.revinfo = revinfo;
    }
    public MailtemplateAud(MailtemplateAudId id, Revinfo revinfo, Byte revtype, String query, Boolean queryMod, String subject, Boolean subjectMod, String text, Boolean textMod, String name, Boolean nameMod, Date changed, Boolean changedMod, String changedby, Boolean changedbyMod, Date created, Boolean createdMod, String createdby, Boolean createdbyMod, String owner, Boolean ownerMod, Boolean bcc, Boolean bccMod, Boolean cc, Boolean ccMod, Boolean savetext, Boolean savetextMod, Boolean sms, Boolean smsMod, Boolean alternativetext, Boolean alternativetextMod) {
       this.id = id;
       this.revinfo = revinfo;
       this.revtype = revtype;
       this.query = query;
       this.queryMod = queryMod;
       this.subject = subject;
       this.subjectMod = subjectMod;
       this.text = text;
       this.textMod = textMod;
       this.name = name;
       this.nameMod = nameMod;
       this.changed = changed;
       this.changedMod = changedMod;
       this.changedby = changedby;
       this.changedbyMod = changedbyMod;
       this.created = created;
       this.createdMod = createdMod;
       this.createdby = createdby;
       this.createdbyMod = createdbyMod;
       this.owner = owner;
       this.ownerMod = ownerMod;
       this.bcc = bcc;
       this.bccMod = bccMod;
       this.cc = cc;
       this.ccMod = ccMod;
       this.savetext = savetext;
       this.savetextMod = savetextMod;
       this.sms = sms;
       this.smsMod = smsMod;
       this.alternativetext = alternativetext;
       this.alternativetextMod = alternativetextMod;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="ID", nullable=false) ), 
        @AttributeOverride(name="rev", column=@Column(name="REV", nullable=false) ) } )
    public MailtemplateAudId getId() {
        return this.id;
    }
    
    public void setId(MailtemplateAudId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REV", nullable=false, insertable=false, updatable=false)
    public Revinfo getRevinfo() {
        return this.revinfo;
    }
    
    public void setRevinfo(Revinfo revinfo) {
        this.revinfo = revinfo;
    }

    
    @Column(name="REVTYPE")
    public Byte getRevtype() {
        return this.revtype;
    }
    
    public void setRevtype(Byte revtype) {
        this.revtype = revtype;
    }

    
    @Column(name="QUERY")
    public String getQuery() {
        return this.query;
    }
    
    public void setQuery(String query) {
        this.query = query;
    }

    
    @Column(name="QUERY_MOD")
    public Boolean getQueryMod() {
        return this.queryMod;
    }
    
    public void setQueryMod(Boolean queryMod) {
        this.queryMod = queryMod;
    }

    
    @Column(name="SUBJECT")
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    
    @Column(name="SUBJECT_MOD")
    public Boolean getSubjectMod() {
        return this.subjectMod;
    }
    
    public void setSubjectMod(Boolean subjectMod) {
        this.subjectMod = subjectMod;
    }

    
    @Column(name="TEXT", length=40960)
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }

    
    @Column(name="TEXT_MOD")
    public Boolean getTextMod() {
        return this.textMod;
    }
    
    public void setTextMod(Boolean textMod) {
        this.textMod = textMod;
    }

    
    @Column(name="NAME")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="NAME_MOD")
    public Boolean getNameMod() {
        return this.nameMod;
    }
    
    public void setNameMod(Boolean nameMod) {
        this.nameMod = nameMod;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CHANGED", length=23)
    public Date getChanged() {
        return this.changed;
    }
    
    public void setChanged(Date changed) {
        this.changed = changed;
    }

    
    @Column(name="CHANGED_MOD")
    public Boolean getChangedMod() {
        return this.changedMod;
    }
    
    public void setChangedMod(Boolean changedMod) {
        this.changedMod = changedMod;
    }

    
    @Column(name="CHANGEDBY")
    public String getChangedby() {
        return this.changedby;
    }
    
    public void setChangedby(String changedby) {
        this.changedby = changedby;
    }

    
    @Column(name="CHANGEDBY_MOD")
    public Boolean getChangedbyMod() {
        return this.changedbyMod;
    }
    
    public void setChangedbyMod(Boolean changedbyMod) {
        this.changedbyMod = changedbyMod;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    
    @Column(name="CREATED_MOD")
    public Boolean getCreatedMod() {
        return this.createdMod;
    }
    
    public void setCreatedMod(Boolean createdMod) {
        this.createdMod = createdMod;
    }

    
    @Column(name="CREATEDBY")
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    
    @Column(name="CREATEDBY_MOD")
    public Boolean getCreatedbyMod() {
        return this.createdbyMod;
    }
    
    public void setCreatedbyMod(Boolean createdbyMod) {
        this.createdbyMod = createdbyMod;
    }

    
    @Column(name="OWNER", length=64)
    public String getOwner() {
        return this.owner;
    }
    
    public void setOwner(String owner) {
        this.owner = owner;
    }

    
    @Column(name="OWNER_MOD")
    public Boolean getOwnerMod() {
        return this.ownerMod;
    }
    
    public void setOwnerMod(Boolean ownerMod) {
        this.ownerMod = ownerMod;
    }

    
    @Column(name="BCC")
    public Boolean getBcc() {
        return this.bcc;
    }
    
    public void setBcc(Boolean bcc) {
        this.bcc = bcc;
    }

    
    @Column(name="BCC_MOD")
    public Boolean getBccMod() {
        return this.bccMod;
    }
    
    public void setBccMod(Boolean bccMod) {
        this.bccMod = bccMod;
    }

    
    @Column(name="CC")
    public Boolean getCc() {
        return this.cc;
    }
    
    public void setCc(Boolean cc) {
        this.cc = cc;
    }

    
    @Column(name="CC_MOD")
    public Boolean getCcMod() {
        return this.ccMod;
    }
    
    public void setCcMod(Boolean ccMod) {
        this.ccMod = ccMod;
    }

    
    @Column(name="SAVETEXT")
    public Boolean getSavetext() {
        return this.savetext;
    }
    
    public void setSavetext(Boolean savetext) {
        this.savetext = savetext;
    }

    
    @Column(name="SAVETEXT_MOD")
    public Boolean getSavetextMod() {
        return this.savetextMod;
    }
    
    public void setSavetextMod(Boolean savetextMod) {
        this.savetextMod = savetextMod;
    }

    
    @Column(name="SMS")
    public Boolean getSms() {
        return this.sms;
    }
    
    public void setSms(Boolean sms) {
        this.sms = sms;
    }

    
    @Column(name="SMS_MOD")
    public Boolean getSmsMod() {
        return this.smsMod;
    }
    
    public void setSmsMod(Boolean smsMod) {
        this.smsMod = smsMod;
    }

    
    @Column(name="ALTERNATIVETEXT")
    public Boolean getAlternativetext() {
        return this.alternativetext;
    }
    
    public void setAlternativetext(Boolean alternativetext) {
        this.alternativetext = alternativetext;
    }

    
    @Column(name="ALTERNATIVETEXT_MOD")
    public Boolean getAlternativetextMod() {
        return this.alternativetextMod;
    }
    
    public void setAlternativetextMod(Boolean alternativetextMod) {
        this.alternativetextMod = alternativetextMod;
    }




}


