package at.tfr.pfad.model;
// Generated Feb 2, 2021, 9:27:45 PM by Hibernate Tools 5.2.11.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MemberAud generated by hbm2java
 */
@Entity
@Table(name="MEMBER_AUD")
public class MemberAud  implements java.io.Serializable {


     private MemberAudId id;
     private Revinfo revinfo;
     private Byte revtype;
     private Boolean aktiv;
     private Boolean aktivMod;
     private Boolean aktivextern;
     private Boolean aktivexternMod;
     private Boolean alter;
     private Boolean alterMod;
     private String anrede;
     private Boolean anredeMod;
     private String bvkey;
     private Boolean bvkeyMod;
     private Date changed;
     private Boolean changedMod;
     private String changedby;
     private Boolean changedbyMod;
     private Date created;
     private Boolean createdMod;
     private String createdby;
     private Boolean createdbyMod;
     private String email;
     private Boolean emailMod;
     private Integer gebjahr;
     private Boolean gebjahrMod;
     private Integer gebmonat;
     private Boolean gebmonatMod;
     private Integer gebtag;
     private Boolean gebtagMod;
     private String geschlecht;
     private Boolean geschlechtMod;
     private Boolean gilde;
     private Boolean gildeMod;
     private String gruppenschluessel;
     private Boolean gruppenschluesselMod;
     private Boolean infomail;
     private Boolean infomailMod;
     private String name;
     private Boolean nameMod;
     private String ort;
     private Boolean ortMod;
     private Long personenkey;
     private Boolean personenkeyMod;
     private String plz;
     private Boolean plzMod;
     private String religion;
     private Boolean religionMod;
     private String rolle;
     private Boolean rolleMod;
     private String strasse;
     private Boolean strasseMod;
     private Boolean support;
     private Boolean supportMod;
     private String telefon;
     private Boolean telefonMod;
     private String titel;
     private Boolean titelMod;
     private Boolean trail;
     private Boolean trailMod;
     private String vorname;
     private Boolean vornameMod;
     private Long vollzahlerId;
     private Boolean vollzahlerMod;
     private Boolean bookingsMod;
     private Boolean funktionenMod;
     private Boolean parentsMod;
     private Boolean paymentsMod;
     private Boolean reducedMod;
     private Boolean siblingsMod;
     private Long truppId;
     private Boolean truppMod;
     private boolean free;
     private Boolean freeMod;
     private boolean dead;
     private Boolean deadMod;
     private Boolean participationsMod;

    public MemberAud() {
    }

	
    public MemberAud(MemberAudId id, Revinfo revinfo, boolean free, boolean dead) {
        this.id = id;
        this.revinfo = revinfo;
        this.free = free;
        this.dead = dead;
    }
    public MemberAud(MemberAudId id, Revinfo revinfo, Byte revtype, Boolean aktiv, Boolean aktivMod, Boolean aktivextern, Boolean aktivexternMod, Boolean alter, Boolean alterMod, String anrede, Boolean anredeMod, String bvkey, Boolean bvkeyMod, Date changed, Boolean changedMod, String changedby, Boolean changedbyMod, Date created, Boolean createdMod, String createdby, Boolean createdbyMod, String email, Boolean emailMod, Integer gebjahr, Boolean gebjahrMod, Integer gebmonat, Boolean gebmonatMod, Integer gebtag, Boolean gebtagMod, String geschlecht, Boolean geschlechtMod, Boolean gilde, Boolean gildeMod, String gruppenschluessel, Boolean gruppenschluesselMod, Boolean infomail, Boolean infomailMod, String name, Boolean nameMod, String ort, Boolean ortMod, Long personenkey, Boolean personenkeyMod, String plz, Boolean plzMod, String religion, Boolean religionMod, String rolle, Boolean rolleMod, String strasse, Boolean strasseMod, Boolean support, Boolean supportMod, String telefon, Boolean telefonMod, String titel, Boolean titelMod, Boolean trail, Boolean trailMod, String vorname, Boolean vornameMod, Long vollzahlerId, Boolean vollzahlerMod, Boolean bookingsMod, Boolean funktionenMod, Boolean parentsMod, Boolean paymentsMod, Boolean reducedMod, Boolean siblingsMod, Long truppId, Boolean truppMod, boolean free, Boolean freeMod, boolean dead, Boolean deadMod, Boolean participationsMod) {
       this.id = id;
       this.revinfo = revinfo;
       this.revtype = revtype;
       this.aktiv = aktiv;
       this.aktivMod = aktivMod;
       this.aktivextern = aktivextern;
       this.aktivexternMod = aktivexternMod;
       this.alter = alter;
       this.alterMod = alterMod;
       this.anrede = anrede;
       this.anredeMod = anredeMod;
       this.bvkey = bvkey;
       this.bvkeyMod = bvkeyMod;
       this.changed = changed;
       this.changedMod = changedMod;
       this.changedby = changedby;
       this.changedbyMod = changedbyMod;
       this.created = created;
       this.createdMod = createdMod;
       this.createdby = createdby;
       this.createdbyMod = createdbyMod;
       this.email = email;
       this.emailMod = emailMod;
       this.gebjahr = gebjahr;
       this.gebjahrMod = gebjahrMod;
       this.gebmonat = gebmonat;
       this.gebmonatMod = gebmonatMod;
       this.gebtag = gebtag;
       this.gebtagMod = gebtagMod;
       this.geschlecht = geschlecht;
       this.geschlechtMod = geschlechtMod;
       this.gilde = gilde;
       this.gildeMod = gildeMod;
       this.gruppenschluessel = gruppenschluessel;
       this.gruppenschluesselMod = gruppenschluesselMod;
       this.infomail = infomail;
       this.infomailMod = infomailMod;
       this.name = name;
       this.nameMod = nameMod;
       this.ort = ort;
       this.ortMod = ortMod;
       this.personenkey = personenkey;
       this.personenkeyMod = personenkeyMod;
       this.plz = plz;
       this.plzMod = plzMod;
       this.religion = religion;
       this.religionMod = religionMod;
       this.rolle = rolle;
       this.rolleMod = rolleMod;
       this.strasse = strasse;
       this.strasseMod = strasseMod;
       this.support = support;
       this.supportMod = supportMod;
       this.telefon = telefon;
       this.telefonMod = telefonMod;
       this.titel = titel;
       this.titelMod = titelMod;
       this.trail = trail;
       this.trailMod = trailMod;
       this.vorname = vorname;
       this.vornameMod = vornameMod;
       this.vollzahlerId = vollzahlerId;
       this.vollzahlerMod = vollzahlerMod;
       this.bookingsMod = bookingsMod;
       this.funktionenMod = funktionenMod;
       this.parentsMod = parentsMod;
       this.paymentsMod = paymentsMod;
       this.reducedMod = reducedMod;
       this.siblingsMod = siblingsMod;
       this.truppId = truppId;
       this.truppMod = truppMod;
       this.free = free;
       this.freeMod = freeMod;
       this.dead = dead;
       this.deadMod = deadMod;
       this.participationsMod = participationsMod;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="ID", nullable=false) ), 
        @AttributeOverride(name="rev", column=@Column(name="REV", nullable=false) ) } )
    public MemberAudId getId() {
        return this.id;
    }
    
    public void setId(MemberAudId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REV", nullable=false, insertable=false, updatable=false)
    public Revinfo getRevinfo() {
        return this.revinfo;
    }
    
    public void setRevinfo(Revinfo revinfo) {
        this.revinfo = revinfo;
    }

    
    @Column(name="REVTYPE")
    public Byte getRevtype() {
        return this.revtype;
    }
    
    public void setRevtype(Byte revtype) {
        this.revtype = revtype;
    }

    
    @Column(name="AKTIV")
    public Boolean getAktiv() {
        return this.aktiv;
    }
    
    public void setAktiv(Boolean aktiv) {
        this.aktiv = aktiv;
    }

    
    @Column(name="AKTIV_MOD")
    public Boolean getAktivMod() {
        return this.aktivMod;
    }
    
    public void setAktivMod(Boolean aktivMod) {
        this.aktivMod = aktivMod;
    }

    
    @Column(name="AKTIVEXTERN")
    public Boolean getAktivextern() {
        return this.aktivextern;
    }
    
    public void setAktivextern(Boolean aktivextern) {
        this.aktivextern = aktivextern;
    }

    
    @Column(name="AKTIVEXTERN_MOD")
    public Boolean getAktivexternMod() {
        return this.aktivexternMod;
    }
    
    public void setAktivexternMod(Boolean aktivexternMod) {
        this.aktivexternMod = aktivexternMod;
    }

    
    @Column(name="ALTER")
    public Boolean getAlter() {
        return this.alter;
    }
    
    public void setAlter(Boolean alter) {
        this.alter = alter;
    }

    
    @Column(name="ALTER_MOD")
    public Boolean getAlterMod() {
        return this.alterMod;
    }
    
    public void setAlterMod(Boolean alterMod) {
        this.alterMod = alterMod;
    }

    
    @Column(name="ANREDE")
    public String getAnrede() {
        return this.anrede;
    }
    
    public void setAnrede(String anrede) {
        this.anrede = anrede;
    }

    
    @Column(name="ANREDE_MOD")
    public Boolean getAnredeMod() {
        return this.anredeMod;
    }
    
    public void setAnredeMod(Boolean anredeMod) {
        this.anredeMod = anredeMod;
    }

    
    @Column(name="BVKEY")
    public String getBvkey() {
        return this.bvkey;
    }
    
    public void setBvkey(String bvkey) {
        this.bvkey = bvkey;
    }

    
    @Column(name="BVKEY_MOD")
    public Boolean getBvkeyMod() {
        return this.bvkeyMod;
    }
    
    public void setBvkeyMod(Boolean bvkeyMod) {
        this.bvkeyMod = bvkeyMod;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CHANGED", length=23)
    public Date getChanged() {
        return this.changed;
    }
    
    public void setChanged(Date changed) {
        this.changed = changed;
    }

    
    @Column(name="CHANGED_MOD")
    public Boolean getChangedMod() {
        return this.changedMod;
    }
    
    public void setChangedMod(Boolean changedMod) {
        this.changedMod = changedMod;
    }

    
    @Column(name="CHANGEDBY")
    public String getChangedby() {
        return this.changedby;
    }
    
    public void setChangedby(String changedby) {
        this.changedby = changedby;
    }

    
    @Column(name="CHANGEDBY_MOD")
    public Boolean getChangedbyMod() {
        return this.changedbyMod;
    }
    
    public void setChangedbyMod(Boolean changedbyMod) {
        this.changedbyMod = changedbyMod;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    
    @Column(name="CREATED_MOD")
    public Boolean getCreatedMod() {
        return this.createdMod;
    }
    
    public void setCreatedMod(Boolean createdMod) {
        this.createdMod = createdMod;
    }

    
    @Column(name="CREATEDBY")
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    
    @Column(name="CREATEDBY_MOD")
    public Boolean getCreatedbyMod() {
        return this.createdbyMod;
    }
    
    public void setCreatedbyMod(Boolean createdbyMod) {
        this.createdbyMod = createdbyMod;
    }

    
    @Column(name="EMAIL")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="EMAIL_MOD")
    public Boolean getEmailMod() {
        return this.emailMod;
    }
    
    public void setEmailMod(Boolean emailMod) {
        this.emailMod = emailMod;
    }

    
    @Column(name="GEBJAHR")
    public Integer getGebjahr() {
        return this.gebjahr;
    }
    
    public void setGebjahr(Integer gebjahr) {
        this.gebjahr = gebjahr;
    }

    
    @Column(name="GEBJAHR_MOD")
    public Boolean getGebjahrMod() {
        return this.gebjahrMod;
    }
    
    public void setGebjahrMod(Boolean gebjahrMod) {
        this.gebjahrMod = gebjahrMod;
    }

    
    @Column(name="GEBMONAT")
    public Integer getGebmonat() {
        return this.gebmonat;
    }
    
    public void setGebmonat(Integer gebmonat) {
        this.gebmonat = gebmonat;
    }

    
    @Column(name="GEBMONAT_MOD")
    public Boolean getGebmonatMod() {
        return this.gebmonatMod;
    }
    
    public void setGebmonatMod(Boolean gebmonatMod) {
        this.gebmonatMod = gebmonatMod;
    }

    
    @Column(name="GEBTAG")
    public Integer getGebtag() {
        return this.gebtag;
    }
    
    public void setGebtag(Integer gebtag) {
        this.gebtag = gebtag;
    }

    
    @Column(name="GEBTAG_MOD")
    public Boolean getGebtagMod() {
        return this.gebtagMod;
    }
    
    public void setGebtagMod(Boolean gebtagMod) {
        this.gebtagMod = gebtagMod;
    }

    
    @Column(name="GESCHLECHT")
    public String getGeschlecht() {
        return this.geschlecht;
    }
    
    public void setGeschlecht(String geschlecht) {
        this.geschlecht = geschlecht;
    }

    
    @Column(name="GESCHLECHT_MOD")
    public Boolean getGeschlechtMod() {
        return this.geschlechtMod;
    }
    
    public void setGeschlechtMod(Boolean geschlechtMod) {
        this.geschlechtMod = geschlechtMod;
    }

    
    @Column(name="GILDE")
    public Boolean getGilde() {
        return this.gilde;
    }
    
    public void setGilde(Boolean gilde) {
        this.gilde = gilde;
    }

    
    @Column(name="GILDE_MOD")
    public Boolean getGildeMod() {
        return this.gildeMod;
    }
    
    public void setGildeMod(Boolean gildeMod) {
        this.gildeMod = gildeMod;
    }

    
    @Column(name="GRUPPENSCHLUESSEL")
    public String getGruppenschluessel() {
        return this.gruppenschluessel;
    }
    
    public void setGruppenschluessel(String gruppenschluessel) {
        this.gruppenschluessel = gruppenschluessel;
    }

    
    @Column(name="GRUPPENSCHLUESSEL_MOD")
    public Boolean getGruppenschluesselMod() {
        return this.gruppenschluesselMod;
    }
    
    public void setGruppenschluesselMod(Boolean gruppenschluesselMod) {
        this.gruppenschluesselMod = gruppenschluesselMod;
    }

    
    @Column(name="INFOMAIL")
    public Boolean getInfomail() {
        return this.infomail;
    }
    
    public void setInfomail(Boolean infomail) {
        this.infomail = infomail;
    }

    
    @Column(name="INFOMAIL_MOD")
    public Boolean getInfomailMod() {
        return this.infomailMod;
    }
    
    public void setInfomailMod(Boolean infomailMod) {
        this.infomailMod = infomailMod;
    }

    
    @Column(name="NAME")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="NAME_MOD")
    public Boolean getNameMod() {
        return this.nameMod;
    }
    
    public void setNameMod(Boolean nameMod) {
        this.nameMod = nameMod;
    }

    
    @Column(name="ORT")
    public String getOrt() {
        return this.ort;
    }
    
    public void setOrt(String ort) {
        this.ort = ort;
    }

    
    @Column(name="ORT_MOD")
    public Boolean getOrtMod() {
        return this.ortMod;
    }
    
    public void setOrtMod(Boolean ortMod) {
        this.ortMod = ortMod;
    }

    
    @Column(name="PERSONENKEY")
    public Long getPersonenkey() {
        return this.personenkey;
    }
    
    public void setPersonenkey(Long personenkey) {
        this.personenkey = personenkey;
    }

    
    @Column(name="PERSONENKEY_MOD")
    public Boolean getPersonenkeyMod() {
        return this.personenkeyMod;
    }
    
    public void setPersonenkeyMod(Boolean personenkeyMod) {
        this.personenkeyMod = personenkeyMod;
    }

    
    @Column(name="PLZ")
    public String getPlz() {
        return this.plz;
    }
    
    public void setPlz(String plz) {
        this.plz = plz;
    }

    
    @Column(name="PLZ_MOD")
    public Boolean getPlzMod() {
        return this.plzMod;
    }
    
    public void setPlzMod(Boolean plzMod) {
        this.plzMod = plzMod;
    }

    
    @Column(name="RELIGION")
    public String getReligion() {
        return this.religion;
    }
    
    public void setReligion(String religion) {
        this.religion = religion;
    }

    
    @Column(name="RELIGION_MOD")
    public Boolean getReligionMod() {
        return this.religionMod;
    }
    
    public void setReligionMod(Boolean religionMod) {
        this.religionMod = religionMod;
    }

    
    @Column(name="ROLLE")
    public String getRolle() {
        return this.rolle;
    }
    
    public void setRolle(String rolle) {
        this.rolle = rolle;
    }

    
    @Column(name="ROLLE_MOD")
    public Boolean getRolleMod() {
        return this.rolleMod;
    }
    
    public void setRolleMod(Boolean rolleMod) {
        this.rolleMod = rolleMod;
    }

    
    @Column(name="STRASSE")
    public String getStrasse() {
        return this.strasse;
    }
    
    public void setStrasse(String strasse) {
        this.strasse = strasse;
    }

    
    @Column(name="STRASSE_MOD")
    public Boolean getStrasseMod() {
        return this.strasseMod;
    }
    
    public void setStrasseMod(Boolean strasseMod) {
        this.strasseMod = strasseMod;
    }

    
    @Column(name="SUPPORT")
    public Boolean getSupport() {
        return this.support;
    }
    
    public void setSupport(Boolean support) {
        this.support = support;
    }

    
    @Column(name="SUPPORT_MOD")
    public Boolean getSupportMod() {
        return this.supportMod;
    }
    
    public void setSupportMod(Boolean supportMod) {
        this.supportMod = supportMod;
    }

    
    @Column(name="TELEFON")
    public String getTelefon() {
        return this.telefon;
    }
    
    public void setTelefon(String telefon) {
        this.telefon = telefon;
    }

    
    @Column(name="TELEFON_MOD")
    public Boolean getTelefonMod() {
        return this.telefonMod;
    }
    
    public void setTelefonMod(Boolean telefonMod) {
        this.telefonMod = telefonMod;
    }

    
    @Column(name="TITEL")
    public String getTitel() {
        return this.titel;
    }
    
    public void setTitel(String titel) {
        this.titel = titel;
    }

    
    @Column(name="TITEL_MOD")
    public Boolean getTitelMod() {
        return this.titelMod;
    }
    
    public void setTitelMod(Boolean titelMod) {
        this.titelMod = titelMod;
    }

    
    @Column(name="TRAIL")
    public Boolean getTrail() {
        return this.trail;
    }
    
    public void setTrail(Boolean trail) {
        this.trail = trail;
    }

    
    @Column(name="TRAIL_MOD")
    public Boolean getTrailMod() {
        return this.trailMod;
    }
    
    public void setTrailMod(Boolean trailMod) {
        this.trailMod = trailMod;
    }

    
    @Column(name="VORNAME")
    public String getVorname() {
        return this.vorname;
    }
    
    public void setVorname(String vorname) {
        this.vorname = vorname;
    }

    
    @Column(name="VORNAME_MOD")
    public Boolean getVornameMod() {
        return this.vornameMod;
    }
    
    public void setVornameMod(Boolean vornameMod) {
        this.vornameMod = vornameMod;
    }

    
    @Column(name="VOLLZAHLER_ID")
    public Long getVollzahlerId() {
        return this.vollzahlerId;
    }
    
    public void setVollzahlerId(Long vollzahlerId) {
        this.vollzahlerId = vollzahlerId;
    }

    
    @Column(name="VOLLZAHLER_MOD")
    public Boolean getVollzahlerMod() {
        return this.vollzahlerMod;
    }
    
    public void setVollzahlerMod(Boolean vollzahlerMod) {
        this.vollzahlerMod = vollzahlerMod;
    }

    
    @Column(name="BOOKINGS_MOD")
    public Boolean getBookingsMod() {
        return this.bookingsMod;
    }
    
    public void setBookingsMod(Boolean bookingsMod) {
        this.bookingsMod = bookingsMod;
    }

    
    @Column(name="FUNKTIONEN_MOD")
    public Boolean getFunktionenMod() {
        return this.funktionenMod;
    }
    
    public void setFunktionenMod(Boolean funktionenMod) {
        this.funktionenMod = funktionenMod;
    }

    
    @Column(name="PARENTS_MOD")
    public Boolean getParentsMod() {
        return this.parentsMod;
    }
    
    public void setParentsMod(Boolean parentsMod) {
        this.parentsMod = parentsMod;
    }

    
    @Column(name="PAYMENTS_MOD")
    public Boolean getPaymentsMod() {
        return this.paymentsMod;
    }
    
    public void setPaymentsMod(Boolean paymentsMod) {
        this.paymentsMod = paymentsMod;
    }

    
    @Column(name="REDUCED_MOD")
    public Boolean getReducedMod() {
        return this.reducedMod;
    }
    
    public void setReducedMod(Boolean reducedMod) {
        this.reducedMod = reducedMod;
    }

    
    @Column(name="SIBLINGS_MOD")
    public Boolean getSiblingsMod() {
        return this.siblingsMod;
    }
    
    public void setSiblingsMod(Boolean siblingsMod) {
        this.siblingsMod = siblingsMod;
    }

    
    @Column(name="TRUPP_ID")
    public Long getTruppId() {
        return this.truppId;
    }
    
    public void setTruppId(Long truppId) {
        this.truppId = truppId;
    }

    
    @Column(name="TRUPP_MOD")
    public Boolean getTruppMod() {
        return this.truppMod;
    }
    
    public void setTruppMod(Boolean truppMod) {
        this.truppMod = truppMod;
    }

    
    @Column(name="FREE", nullable=false)
    public boolean isFree() {
        return this.free;
    }
    
    public void setFree(boolean free) {
        this.free = free;
    }

    
    @Column(name="FREE_MOD")
    public Boolean getFreeMod() {
        return this.freeMod;
    }
    
    public void setFreeMod(Boolean freeMod) {
        this.freeMod = freeMod;
    }

    
    @Column(name="DEAD", nullable=false)
    public boolean isDead() {
        return this.dead;
    }
    
    public void setDead(boolean dead) {
        this.dead = dead;
    }

    
    @Column(name="DEAD_MOD")
    public Boolean getDeadMod() {
        return this.deadMod;
    }
    
    public void setDeadMod(Boolean deadMod) {
        this.deadMod = deadMod;
    }

    
    @Column(name="PARTICIPATIONS_MOD")
    public Boolean getParticipationsMod() {
        return this.participationsMod;
    }
    
    public void setParticipationsMod(Boolean participationsMod) {
        this.participationsMod = participationsMod;
    }




}


