package at.tfr.pfad.model;
// Generated Feb 2, 2021, 9:27:45 PM by Hibernate Tools 5.2.11.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MemberFunctionAudId generated by hbm2java
 */
@Embeddable
public class MemberFunctionAudId  implements java.io.Serializable {


     private int rev;
     private long memberId;
     private long funktionenId;

    public MemberFunctionAudId() {
    }

    public MemberFunctionAudId(int rev, long memberId, long funktionenId) {
       this.rev = rev;
       this.memberId = memberId;
       this.funktionenId = funktionenId;
    }
   


    @Column(name="REV", nullable=false)
    public int getRev() {
        return this.rev;
    }
    
    public void setRev(int rev) {
        this.rev = rev;
    }


    @Column(name="MEMBER_ID", nullable=false)
    public long getMemberId() {
        return this.memberId;
    }
    
    public void setMemberId(long memberId) {
        this.memberId = memberId;
    }


    @Column(name="FUNKTIONEN_ID", nullable=false)
    public long getFunktionenId() {
        return this.funktionenId;
    }
    
    public void setFunktionenId(long funktionenId) {
        this.funktionenId = funktionenId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MemberFunctionAudId) ) return false;
		 MemberFunctionAudId castOther = ( MemberFunctionAudId ) other; 
         
		 return (this.getRev()==castOther.getRev())
 && (this.getMemberId()==castOther.getMemberId())
 && (this.getFunktionenId()==castOther.getFunktionenId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRev();
         result = 37 * result + (int) this.getMemberId();
         result = 37 * result + (int) this.getFunktionenId();
         return result;
   }   


}


