package at.tfr.pfad.model;
// Generated Feb 2, 2021, 9:27:45 PM by Hibernate Tools 5.2.11.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ParticipationAud generated by hbm2java
 */
@Entity
@Table(name="PARTICIPATION_AUD")
public class ParticipationAud  implements java.io.Serializable {


     private ParticipationAudId id;
     private Revinfo revinfo;
     private Byte revtype;
     private Double amount;
     private Boolean amountMod;
     private Date changed;
     private Boolean changedMod;
     private String changedby;
     private Boolean changedbyMod;
     private String comment;
     private Boolean commentMod;
     private String costtype;
     private Boolean costtypeMod;
     private Date created;
     private Boolean createdMod;
     private String createdby;
     private Boolean createdbyMod;
     private Date end;
     private Boolean endMod;
     private Date start;
     private Boolean startMod;
     private String status;
     private Boolean statusMod;
     private Long memberId;
     private Boolean memberMod;
     private Long trainingId;
     private Boolean trainingMod;

    public ParticipationAud() {
    }

	
    public ParticipationAud(ParticipationAudId id, Revinfo revinfo) {
        this.id = id;
        this.revinfo = revinfo;
    }
    public ParticipationAud(ParticipationAudId id, Revinfo revinfo, Byte revtype, Double amount, Boolean amountMod, Date changed, Boolean changedMod, String changedby, Boolean changedbyMod, String comment, Boolean commentMod, String costtype, Boolean costtypeMod, Date created, Boolean createdMod, String createdby, Boolean createdbyMod, Date end, Boolean endMod, Date start, Boolean startMod, String status, Boolean statusMod, Long memberId, Boolean memberMod, Long trainingId, Boolean trainingMod) {
       this.id = id;
       this.revinfo = revinfo;
       this.revtype = revtype;
       this.amount = amount;
       this.amountMod = amountMod;
       this.changed = changed;
       this.changedMod = changedMod;
       this.changedby = changedby;
       this.changedbyMod = changedbyMod;
       this.comment = comment;
       this.commentMod = commentMod;
       this.costtype = costtype;
       this.costtypeMod = costtypeMod;
       this.created = created;
       this.createdMod = createdMod;
       this.createdby = createdby;
       this.createdbyMod = createdbyMod;
       this.end = end;
       this.endMod = endMod;
       this.start = start;
       this.startMod = startMod;
       this.status = status;
       this.statusMod = statusMod;
       this.memberId = memberId;
       this.memberMod = memberMod;
       this.trainingId = trainingId;
       this.trainingMod = trainingMod;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="ID", nullable=false) ), 
        @AttributeOverride(name="rev", column=@Column(name="REV", nullable=false) ) } )
    public ParticipationAudId getId() {
        return this.id;
    }
    
    public void setId(ParticipationAudId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REV", nullable=false, insertable=false, updatable=false)
    public Revinfo getRevinfo() {
        return this.revinfo;
    }
    
    public void setRevinfo(Revinfo revinfo) {
        this.revinfo = revinfo;
    }

    
    @Column(name="REVTYPE")
    public Byte getRevtype() {
        return this.revtype;
    }
    
    public void setRevtype(Byte revtype) {
        this.revtype = revtype;
    }

    
    @Column(name="AMOUNT", precision=17, scale=0)
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    
    @Column(name="AMOUNT_MOD")
    public Boolean getAmountMod() {
        return this.amountMod;
    }
    
    public void setAmountMod(Boolean amountMod) {
        this.amountMod = amountMod;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CHANGED", length=23)
    public Date getChanged() {
        return this.changed;
    }
    
    public void setChanged(Date changed) {
        this.changed = changed;
    }

    
    @Column(name="CHANGED_MOD")
    public Boolean getChangedMod() {
        return this.changedMod;
    }
    
    public void setChangedMod(Boolean changedMod) {
        this.changedMod = changedMod;
    }

    
    @Column(name="CHANGEDBY")
    public String getChangedby() {
        return this.changedby;
    }
    
    public void setChangedby(String changedby) {
        this.changedby = changedby;
    }

    
    @Column(name="CHANGEDBY_MOD")
    public Boolean getChangedbyMod() {
        return this.changedbyMod;
    }
    
    public void setChangedbyMod(Boolean changedbyMod) {
        this.changedbyMod = changedbyMod;
    }

    
    @Column(name="COMMENT")
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }

    
    @Column(name="COMMENT_MOD")
    public Boolean getCommentMod() {
        return this.commentMod;
    }
    
    public void setCommentMod(Boolean commentMod) {
        this.commentMod = commentMod;
    }

    
    @Column(name="COSTTYPE")
    public String getCosttype() {
        return this.costtype;
    }
    
    public void setCosttype(String costtype) {
        this.costtype = costtype;
    }

    
    @Column(name="COSTTYPE_MOD")
    public Boolean getCosttypeMod() {
        return this.costtypeMod;
    }
    
    public void setCosttypeMod(Boolean costtypeMod) {
        this.costtypeMod = costtypeMod;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    
    @Column(name="CREATED_MOD")
    public Boolean getCreatedMod() {
        return this.createdMod;
    }
    
    public void setCreatedMod(Boolean createdMod) {
        this.createdMod = createdMod;
    }

    
    @Column(name="CREATEDBY")
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    
    @Column(name="CREATEDBY_MOD")
    public Boolean getCreatedbyMod() {
        return this.createdbyMod;
    }
    
    public void setCreatedbyMod(Boolean createdbyMod) {
        this.createdbyMod = createdbyMod;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="END", length=8)
    public Date getEnd() {
        return this.end;
    }
    
    public void setEnd(Date end) {
        this.end = end;
    }

    
    @Column(name="END_MOD")
    public Boolean getEndMod() {
        return this.endMod;
    }
    
    public void setEndMod(Boolean endMod) {
        this.endMod = endMod;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="START", length=8)
    public Date getStart() {
        return this.start;
    }
    
    public void setStart(Date start) {
        this.start = start;
    }

    
    @Column(name="START_MOD")
    public Boolean getStartMod() {
        return this.startMod;
    }
    
    public void setStartMod(Boolean startMod) {
        this.startMod = startMod;
    }

    
    @Column(name="STATUS")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="STATUS_MOD")
    public Boolean getStatusMod() {
        return this.statusMod;
    }
    
    public void setStatusMod(Boolean statusMod) {
        this.statusMod = statusMod;
    }

    
    @Column(name="MEMBER_ID")
    public Long getMemberId() {
        return this.memberId;
    }
    
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    
    @Column(name="MEMBER_MOD")
    public Boolean getMemberMod() {
        return this.memberMod;
    }
    
    public void setMemberMod(Boolean memberMod) {
        this.memberMod = memberMod;
    }

    
    @Column(name="TRAINING_ID")
    public Long getTrainingId() {
        return this.trainingId;
    }
    
    public void setTrainingId(Long trainingId) {
        this.trainingId = trainingId;
    }

    
    @Column(name="TRAINING_MOD")
    public Boolean getTrainingMod() {
        return this.trainingMod;
    }
    
    public void setTrainingMod(Boolean trainingMod) {
        this.trainingMod = trainingMod;
    }




}


