package at.tfr.pfad.model;
// Generated Feb 2, 2021, 9:27:45 PM by Hibernate Tools 5.2.11.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PaymentAud generated by hbm2java
 */
@Entity
@Table(name="PAYMENT_AUD")
public class PaymentAud  implements java.io.Serializable {


     private PaymentAudId id;
     private Revinfo revinfo;
     private Byte revtype;
     private String comment;
     private Boolean commentMod;
     private Boolean finished;
     private Boolean finishedMod;
     private Date paymentdate;
     private Boolean paymentdateMod;
     private String type;
     private Boolean typeMod;
     private Boolean bookingsMod;
     private Long payerId;
     private Boolean payerMod;
     private Date changed;
     private Boolean changedMod;
     private String changedby;
     private Boolean changedbyMod;
     private Date created;
     private Boolean createdMod;
     private String createdby;
     private Boolean createdbyMod;
     private Double amount;
     private Boolean amountMod;
     private Boolean aconto;
     private Boolean acontoMod;
     private Boolean payeridMod;
     private String payeriban;
     private Boolean payeribanMod;

    public PaymentAud() {
    }

	
    public PaymentAud(PaymentAudId id, Revinfo revinfo) {
        this.id = id;
        this.revinfo = revinfo;
    }
    public PaymentAud(PaymentAudId id, Revinfo revinfo, Byte revtype, String comment, Boolean commentMod, Boolean finished, Boolean finishedMod, Date paymentdate, Boolean paymentdateMod, String type, Boolean typeMod, Boolean bookingsMod, Long payerId, Boolean payerMod, Date changed, Boolean changedMod, String changedby, Boolean changedbyMod, Date created, Boolean createdMod, String createdby, Boolean createdbyMod, Double amount, Boolean amountMod, Boolean aconto, Boolean acontoMod, Boolean payeridMod, String payeriban, Boolean payeribanMod) {
       this.id = id;
       this.revinfo = revinfo;
       this.revtype = revtype;
       this.comment = comment;
       this.commentMod = commentMod;
       this.finished = finished;
       this.finishedMod = finishedMod;
       this.paymentdate = paymentdate;
       this.paymentdateMod = paymentdateMod;
       this.type = type;
       this.typeMod = typeMod;
       this.bookingsMod = bookingsMod;
       this.payerId = payerId;
       this.payerMod = payerMod;
       this.changed = changed;
       this.changedMod = changedMod;
       this.changedby = changedby;
       this.changedbyMod = changedbyMod;
       this.created = created;
       this.createdMod = createdMod;
       this.createdby = createdby;
       this.createdbyMod = createdbyMod;
       this.amount = amount;
       this.amountMod = amountMod;
       this.aconto = aconto;
       this.acontoMod = acontoMod;
       this.payeridMod = payeridMod;
       this.payeriban = payeriban;
       this.payeribanMod = payeribanMod;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="ID", nullable=false) ), 
        @AttributeOverride(name="rev", column=@Column(name="REV", nullable=false) ) } )
    public PaymentAudId getId() {
        return this.id;
    }
    
    public void setId(PaymentAudId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REV", nullable=false, insertable=false, updatable=false)
    public Revinfo getRevinfo() {
        return this.revinfo;
    }
    
    public void setRevinfo(Revinfo revinfo) {
        this.revinfo = revinfo;
    }

    
    @Column(name="REVTYPE")
    public Byte getRevtype() {
        return this.revtype;
    }
    
    public void setRevtype(Byte revtype) {
        this.revtype = revtype;
    }

    
    @Column(name="COMMENT")
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }

    
    @Column(name="COMMENT_MOD")
    public Boolean getCommentMod() {
        return this.commentMod;
    }
    
    public void setCommentMod(Boolean commentMod) {
        this.commentMod = commentMod;
    }

    
    @Column(name="FINISHED")
    public Boolean getFinished() {
        return this.finished;
    }
    
    public void setFinished(Boolean finished) {
        this.finished = finished;
    }

    
    @Column(name="FINISHED_MOD")
    public Boolean getFinishedMod() {
        return this.finishedMod;
    }
    
    public void setFinishedMod(Boolean finishedMod) {
        this.finishedMod = finishedMod;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PAYMENTDATE", length=23)
    public Date getPaymentdate() {
        return this.paymentdate;
    }
    
    public void setPaymentdate(Date paymentdate) {
        this.paymentdate = paymentdate;
    }

    
    @Column(name="PAYMENTDATE_MOD")
    public Boolean getPaymentdateMod() {
        return this.paymentdateMod;
    }
    
    public void setPaymentdateMod(Boolean paymentdateMod) {
        this.paymentdateMod = paymentdateMod;
    }

    
    @Column(name="TYPE")
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="TYPE_MOD")
    public Boolean getTypeMod() {
        return this.typeMod;
    }
    
    public void setTypeMod(Boolean typeMod) {
        this.typeMod = typeMod;
    }

    
    @Column(name="BOOKINGS_MOD")
    public Boolean getBookingsMod() {
        return this.bookingsMod;
    }
    
    public void setBookingsMod(Boolean bookingsMod) {
        this.bookingsMod = bookingsMod;
    }

    
    @Column(name="PAYER_ID")
    public Long getPayerId() {
        return this.payerId;
    }
    
    public void setPayerId(Long payerId) {
        this.payerId = payerId;
    }

    
    @Column(name="PAYER_MOD")
    public Boolean getPayerMod() {
        return this.payerMod;
    }
    
    public void setPayerMod(Boolean payerMod) {
        this.payerMod = payerMod;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CHANGED", length=23)
    public Date getChanged() {
        return this.changed;
    }
    
    public void setChanged(Date changed) {
        this.changed = changed;
    }

    
    @Column(name="CHANGED_MOD")
    public Boolean getChangedMod() {
        return this.changedMod;
    }
    
    public void setChangedMod(Boolean changedMod) {
        this.changedMod = changedMod;
    }

    
    @Column(name="CHANGEDBY")
    public String getChangedby() {
        return this.changedby;
    }
    
    public void setChangedby(String changedby) {
        this.changedby = changedby;
    }

    
    @Column(name="CHANGEDBY_MOD")
    public Boolean getChangedbyMod() {
        return this.changedbyMod;
    }
    
    public void setChangedbyMod(Boolean changedbyMod) {
        this.changedbyMod = changedbyMod;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    
    @Column(name="CREATED_MOD")
    public Boolean getCreatedMod() {
        return this.createdMod;
    }
    
    public void setCreatedMod(Boolean createdMod) {
        this.createdMod = createdMod;
    }

    
    @Column(name="CREATEDBY")
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    
    @Column(name="CREATEDBY_MOD")
    public Boolean getCreatedbyMod() {
        return this.createdbyMod;
    }
    
    public void setCreatedbyMod(Boolean createdbyMod) {
        this.createdbyMod = createdbyMod;
    }

    
    @Column(name="AMOUNT", precision=17, scale=0)
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    
    @Column(name="AMOUNT_MOD")
    public Boolean getAmountMod() {
        return this.amountMod;
    }
    
    public void setAmountMod(Boolean amountMod) {
        this.amountMod = amountMod;
    }

    
    @Column(name="ACONTO")
    public Boolean getAconto() {
        return this.aconto;
    }
    
    public void setAconto(Boolean aconto) {
        this.aconto = aconto;
    }

    
    @Column(name="ACONTO_MOD")
    public Boolean getAcontoMod() {
        return this.acontoMod;
    }
    
    public void setAcontoMod(Boolean acontoMod) {
        this.acontoMod = acontoMod;
    }

    
    @Column(name="PAYERID_MOD")
    public Boolean getPayeridMod() {
        return this.payeridMod;
    }
    
    public void setPayeridMod(Boolean payeridMod) {
        this.payeridMod = payeridMod;
    }

    
    @Column(name="PAYERIBAN")
    public String getPayeriban() {
        return this.payeriban;
    }
    
    public void setPayeriban(String payeriban) {
        this.payeriban = payeriban;
    }

    
    @Column(name="PAYERIBAN_MOD")
    public Boolean getPayeribanMod() {
        return this.payeribanMod;
    }
    
    public void setPayeribanMod(Boolean payeribanMod) {
        this.payeribanMod = payeribanMod;
    }




}


