package at.tfr.pfad.model;
// Generated Feb 2, 2021, 9:27:45 PM by Hibernate Tools 5.2.11.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PaymentBookingAudId generated by hbm2java
 */
@Embeddable
public class PaymentBookingAudId  implements java.io.Serializable {


     private int rev;
     private long paymentsId;
     private long bookingsId;

    public PaymentBookingAudId() {
    }

    public PaymentBookingAudId(int rev, long paymentsId, long bookingsId) {
       this.rev = rev;
       this.paymentsId = paymentsId;
       this.bookingsId = bookingsId;
    }
   


    @Column(name="REV", nullable=false)
    public int getRev() {
        return this.rev;
    }
    
    public void setRev(int rev) {
        this.rev = rev;
    }


    @Column(name="PAYMENTS_ID", nullable=false)
    public long getPaymentsId() {
        return this.paymentsId;
    }
    
    public void setPaymentsId(long paymentsId) {
        this.paymentsId = paymentsId;
    }


    @Column(name="BOOKINGS_ID", nullable=false)
    public long getBookingsId() {
        return this.bookingsId;
    }
    
    public void setBookingsId(long bookingsId) {
        this.bookingsId = bookingsId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PaymentBookingAudId) ) return false;
		 PaymentBookingAudId castOther = ( PaymentBookingAudId ) other; 
         
		 return (this.getRev()==castOther.getRev())
 && (this.getPaymentsId()==castOther.getPaymentsId())
 && (this.getBookingsId()==castOther.getBookingsId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRev();
         result = 37 * result + (int) this.getPaymentsId();
         result = 37 * result + (int) this.getBookingsId();
         return result;
   }   


}


