package at.tfr.pfad.model;
// Generated Feb 2, 2021, 9:27:45 PM by Hibernate Tools 5.2.11.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SquadMemberAudId generated by hbm2java
 */
@Embeddable
public class SquadMemberAudId  implements java.io.Serializable {


     private int rev;
     private long squadId;
     private long assistantsId;

    public SquadMemberAudId() {
    }

    public SquadMemberAudId(int rev, long squadId, long assistantsId) {
       this.rev = rev;
       this.squadId = squadId;
       this.assistantsId = assistantsId;
    }
   


    @Column(name="REV", nullable=false)
    public int getRev() {
        return this.rev;
    }
    
    public void setRev(int rev) {
        this.rev = rev;
    }


    @Column(name="SQUAD_ID", nullable=false)
    public long getSquadId() {
        return this.squadId;
    }
    
    public void setSquadId(long squadId) {
        this.squadId = squadId;
    }


    @Column(name="ASSISTANTS_ID", nullable=false)
    public long getAssistantsId() {
        return this.assistantsId;
    }
    
    public void setAssistantsId(long assistantsId) {
        this.assistantsId = assistantsId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SquadMemberAudId) ) return false;
		 SquadMemberAudId castOther = ( SquadMemberAudId ) other; 
         
		 return (this.getRev()==castOther.getRev())
 && (this.getSquadId()==castOther.getSquadId())
 && (this.getAssistantsId()==castOther.getAssistantsId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRev();
         result = 37 * result + (int) this.getSquadId();
         result = 37 * result + (int) this.getAssistantsId();
         return result;
   }   


}


