package at.tfr.pfad.model;
// Generated Feb 2, 2021, 9:27:45 PM by Hibernate Tools 5.2.11.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SquadAud generated by hbm2java
 */
@Entity
@Table(name="SQUAD_AUD")
public class SquadAud  implements java.io.Serializable {


     private SquadAudId id;
     private Revinfo revinfo;
     private Byte revtype;
     private Date changed;
     private Boolean changedMod;
     private String changedby;
     private Boolean changedbyMod;
     private Date created;
     private Boolean createdMod;
     private String createdby;
     private Boolean createdbyMod;
     private String login;
     private Boolean loginMod;
     private String name;
     private Boolean nameMod;
     private String type;
     private Boolean typeMod;
     private Boolean assistantsMod;
     private Long leaderfemaleId;
     private Boolean leaderfemaleMod;
     private Long leadermaleId;
     private Boolean leadermaleMod;
     private Boolean scoutsMod;

    public SquadAud() {
    }

	
    public SquadAud(SquadAudId id, Revinfo revinfo) {
        this.id = id;
        this.revinfo = revinfo;
    }
    public SquadAud(SquadAudId id, Revinfo revinfo, Byte revtype, Date changed, Boolean changedMod, String changedby, Boolean changedbyMod, Date created, Boolean createdMod, String createdby, Boolean createdbyMod, String login, Boolean loginMod, String name, Boolean nameMod, String type, Boolean typeMod, Boolean assistantsMod, Long leaderfemaleId, Boolean leaderfemaleMod, Long leadermaleId, Boolean leadermaleMod, Boolean scoutsMod) {
       this.id = id;
       this.revinfo = revinfo;
       this.revtype = revtype;
       this.changed = changed;
       this.changedMod = changedMod;
       this.changedby = changedby;
       this.changedbyMod = changedbyMod;
       this.created = created;
       this.createdMod = createdMod;
       this.createdby = createdby;
       this.createdbyMod = createdbyMod;
       this.login = login;
       this.loginMod = loginMod;
       this.name = name;
       this.nameMod = nameMod;
       this.type = type;
       this.typeMod = typeMod;
       this.assistantsMod = assistantsMod;
       this.leaderfemaleId = leaderfemaleId;
       this.leaderfemaleMod = leaderfemaleMod;
       this.leadermaleId = leadermaleId;
       this.leadermaleMod = leadermaleMod;
       this.scoutsMod = scoutsMod;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="ID", nullable=false) ), 
        @AttributeOverride(name="rev", column=@Column(name="REV", nullable=false) ) } )
    public SquadAudId getId() {
        return this.id;
    }
    
    public void setId(SquadAudId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REV", nullable=false, insertable=false, updatable=false)
    public Revinfo getRevinfo() {
        return this.revinfo;
    }
    
    public void setRevinfo(Revinfo revinfo) {
        this.revinfo = revinfo;
    }

    
    @Column(name="REVTYPE")
    public Byte getRevtype() {
        return this.revtype;
    }
    
    public void setRevtype(Byte revtype) {
        this.revtype = revtype;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CHANGED", length=23)
    public Date getChanged() {
        return this.changed;
    }
    
    public void setChanged(Date changed) {
        this.changed = changed;
    }

    
    @Column(name="CHANGED_MOD")
    public Boolean getChangedMod() {
        return this.changedMod;
    }
    
    public void setChangedMod(Boolean changedMod) {
        this.changedMod = changedMod;
    }

    
    @Column(name="CHANGEDBY")
    public String getChangedby() {
        return this.changedby;
    }
    
    public void setChangedby(String changedby) {
        this.changedby = changedby;
    }

    
    @Column(name="CHANGEDBY_MOD")
    public Boolean getChangedbyMod() {
        return this.changedbyMod;
    }
    
    public void setChangedbyMod(Boolean changedbyMod) {
        this.changedbyMod = changedbyMod;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED", length=23)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    
    @Column(name="CREATED_MOD")
    public Boolean getCreatedMod() {
        return this.createdMod;
    }
    
    public void setCreatedMod(Boolean createdMod) {
        this.createdMod = createdMod;
    }

    
    @Column(name="CREATEDBY")
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    
    @Column(name="CREATEDBY_MOD")
    public Boolean getCreatedbyMod() {
        return this.createdbyMod;
    }
    
    public void setCreatedbyMod(Boolean createdbyMod) {
        this.createdbyMod = createdbyMod;
    }

    
    @Column(name="LOGIN")
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }

    
    @Column(name="LOGIN_MOD")
    public Boolean getLoginMod() {
        return this.loginMod;
    }
    
    public void setLoginMod(Boolean loginMod) {
        this.loginMod = loginMod;
    }

    
    @Column(name="NAME")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="NAME_MOD")
    public Boolean getNameMod() {
        return this.nameMod;
    }
    
    public void setNameMod(Boolean nameMod) {
        this.nameMod = nameMod;
    }

    
    @Column(name="TYPE")
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="TYPE_MOD")
    public Boolean getTypeMod() {
        return this.typeMod;
    }
    
    public void setTypeMod(Boolean typeMod) {
        this.typeMod = typeMod;
    }

    
    @Column(name="ASSISTANTS_MOD")
    public Boolean getAssistantsMod() {
        return this.assistantsMod;
    }
    
    public void setAssistantsMod(Boolean assistantsMod) {
        this.assistantsMod = assistantsMod;
    }

    
    @Column(name="LEADERFEMALE_ID")
    public Long getLeaderfemaleId() {
        return this.leaderfemaleId;
    }
    
    public void setLeaderfemaleId(Long leaderfemaleId) {
        this.leaderfemaleId = leaderfemaleId;
    }

    
    @Column(name="LEADERFEMALE_MOD")
    public Boolean getLeaderfemaleMod() {
        return this.leaderfemaleMod;
    }
    
    public void setLeaderfemaleMod(Boolean leaderfemaleMod) {
        this.leaderfemaleMod = leaderfemaleMod;
    }

    
    @Column(name="LEADERMALE_ID")
    public Long getLeadermaleId() {
        return this.leadermaleId;
    }
    
    public void setLeadermaleId(Long leadermaleId) {
        this.leadermaleId = leadermaleId;
    }

    
    @Column(name="LEADERMALE_MOD")
    public Boolean getLeadermaleMod() {
        return this.leadermaleMod;
    }
    
    public void setLeadermaleMod(Boolean leadermaleMod) {
        this.leadermaleMod = leadermaleMod;
    }

    
    @Column(name="SCOUTS_MOD")
    public Boolean getScoutsMod() {
        return this.scoutsMod;
    }
    
    public void setScoutsMod(Boolean scoutsMod) {
        this.scoutsMod = scoutsMod;
    }




}


